### ISSUE TITLE
adaptive positioning with usePopper vertical position failing in certain circumstances

### ISSUE THREAD

**Issue by vincerubinetti** [floating-ui/react-popper#383]
### Reproduction demo

[test.zip](https://github.com/popperjs/react-popper/files/5080966/test.zip)

Run `yarn install && yarn start`

### What went wrong?

![oR8QhEri51](https://user-images.githubusercontent.com/8326331/90338785-17893300-dfba-11ea-929c-a5c9dea224d4.gif)

I'm trying to make a gallery of images in buttons that shows a larger version of the image on hover. I'm running into these strange issues when using `placement: 'top'`. The tooltip shows fine when it is below the but not when it is above.

Trying changing `placement`, commenting in/out `<Svg/>` zooming in/out, scrolling. I can't narrow down exactly what is causing the problem, but it happens frequently, and in all browsers.

### Packages versions

    "@popperjs/core": "^2.4.4",
    "react-popper": "^2.2.3",

**Comment by vincerubinetti** [comment]
It seems that this fixes it:

```
modifiers: [
      {
        name: 'computeStyles',
        options: {
          adaptive: false, // true by default
        },
      },
    ]
```

**Comment by vincerubinetti** [comment]
Possibly related to [this issue on the popperjs core](https://github.com/popperjs/popper-core/issues/1138), except that I'm not even using `position: relative`.

**Comment by kenticomartinh** [comment]
Not sure if the same issue, but most likely it is.

I am using a rather complex combination but it seems it is a superset of what you have. I included some debug hints, so you may try those ...

What I have is

* React Tippy in headless mode with `inlinePositioning` plugin (Tippy is based on Popper)
* Default positioning: `top`
* Popper element rendered to `document.body`
* `flip` modifier with `fallbackPlacements: ['top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end'],`
* `preventOverflow` modifier with `mainAxis: false, altAxis: true`
* `offset` modifier with dynamic offset calculation

What happens to me is that until the `flip` modifier kicks in, everything is OK

![image](https://user-images.githubusercontent.com/11004903/98542405-29186900-2291-11eb-94c4-1cabe2d1e5a8.png)

But once the `flip` modifier triggers the simulation of the alternative positions, it throws the popper element beyond the fold. Thanks to `offset` and some negative margins I can see it misplaced. Yours may be just below the fold ...

![image](https://user-images.githubusercontent.com/11004903/98542529-5d8c2500-2291-11eb-9072-128203b14b11.png)

When I disable `adaptive` mode, it works OK and properly flips

![image](https://user-images.githubusercontent.com/11004903/98543014-1eaa9f00-2292-11eb-8133-feb9f39a31af.png)

After an agonizing debug session, I narrowed it down to a point where I found out that the popper element has both `top: 0` and `bottom: 0` set at the same time, making its `height` the window height instead of my default height and further calculating offsets with it

![image](https://user-images.githubusercontent.com/11004903/98543663-1a32b600-2293-11eb-9d96-c6d5c14464b4.png)

Upon further debugging, I found out that the `initialStyles` of the `applyStyles` modifier write `top` position but don't reset `bottom` getting the wrapper element into this situation. It seems that it is not aware of the historical styles applied by the `flip` modifier, or the `flip` modifier doesn't reset the complete state.

![image](https://user-images.githubusercontent.com/11004903/98542035-9677ca00-2290-11eb-9656-eca5255ebfa3.png)

Hopefully someone with proper knowledge will pick this information up, and try to find a proper fix for it.

**Comment by vincerubinetti** [comment]
I know this is an upstream error, but does any owner from this repo have the knowledge/time/permissions to fix this in `@popper/core`, or bug one of them to fix it (pressure from dependent library maintainers might hold more weight than random users).

**Comment by happylolonly** [comment]
@FezVrasta for me also not working, do you have any update?

**Comment by happylolonly** [comment]
@vincerubinetti why you closed? how you fixed?

**Comment by vincerubinetti** [comment]
Per my [comment above](https://github.com/floating-ui/react-popper/issues/383#issuecomment-674548445), doctype fixes it. More of a strange consequence of browser quirks mode.

**Comment by happylolonly** [comment]
![Uploading Screenshot 2023-07-11 at 18.14.11.png…]()

**Comment by vincerubinetti** [comment]
Okay just going to reopen for @hejtmii's situation. @happylolonly you probably need to upload a minimal reproduction for yours so they can fix it.

**Comment by happylolonly** [comment]
ok, I can do it little bit later, @FezVrasta do you need more info and possibilities to fix? I see you have new lib

**Comment by FezVrasta** [comment]
👋 the library is in low maintenance mode, everyone should move to Floating UI and its React bindings.

https://github.com/floating-ui/react-popper#%EF%B8%8F-this-library-is-in-maintenance-mode

I don't plan to release additional versions unless they are meant to fix vulnerabilities. Hopefully that makes sense.
